### ISSUE TITLE
Can't use multiple filter at once

### ISSUE THREAD

**Issue by SEED-Foundation** [maxbritto/directus_api_manager#21]
Because  filter: just accept one filter we can not query with multiple filter !

for example here 

```
     Iterable<AnnouncementDirectusModel> list = await directusApiManager.findListOfItems<AnnouncementDirectusModel>(
        fields: '*',
        filter: const PropertyFilter(field: "status", operator: FilterOperator.equals, value: "published"),
      );
```

I can't add an other filter

**Comment by jmjoary** [comment]
You can use multiple filters by using a `LogicalOperatorFilter` object. This class required a `LogicalOperator` and an array of `Filter`. 

```
final Filter filter =
        LogicalOperatorFilter(operator: LogicalOperator.and, children: [
      const PropertyFilter(
          field: "status",
          operator: FilterOperator.equals,
          value: "published"),
      PropertyFilter(
          field: "creator",
          operator: FilterOperator.equals,
          value: currentUser.id),
      ]);
```

By the way, you have also a `RelationFilter` (cf [filter.dart](https://github.com/maxbritto/directus_api_manager/blob/main/lib/src/filter.dart)) which allow to handle the relation between the tables.

**Comment by maxbritto** [comment]
Thanks @jmjoary !
This behaviour does match the 'filter' param behaviour from Directus but it definitely lacks documentation. 
At least to list which filters are actually available within our lib. Maybe we should consider adding this doc at some point
